/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLedgerRouteImport } from './routes/_app.ledger'
import { Route as AppIncomeRouteImport } from './routes/_app.income'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppBudgetsRouteImport } from './routes/_app.budgets'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/income': typeof AppIncomeRoute
  '/ledger': typeof AppLedgerRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/income': typeof AppIncomeRoute
  '/ledger': typeof AppLedgerRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/ledger'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/ledger'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/budgets'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/income'
    | '/_app/ledger'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetsRoute: AppBudgetsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
